#+TITLE: Commands used to generate logs
#+AUTHOR: Matteo Franzil, Valentino Armani, Luis Augusto Dias Knob
#+DATE: 2024-05-28
#+DESCRIPTION: This document contains the commands used to generate the logs for the Audit project
#+OPTIONS: toc:2 
#+PROPERTY: header-args :prologue "exec 2>&1"
#+PROPERTY: header-args+ :epilogue ":"
#+PROPERTY: header-args+ :exports code 
#+PROPERTY: header-args+ :results type code
#+PROPERTY: header-args+ :eval no-export
#+LATEX_HEADER: \usepackage{xcolor}
#+SETUPFILE: latex.setup 

# Unused properties
# #+PROPERTY: header-args:shell :var TERM=dumb
# #+PROPERTY: header-args:shell+ :var EMACS=1
# -*- org-confirm-babel-evaluate: nil -*-

* Clusters of ignored logs
** Endpoints different than api/apis
- Verb: any
- Users: any
- Objects: any
- Endpoints: any other than =/api= or =/apis=
** TODO Control plane components monitoring objects
This has to be investigated further.
- Verb: =watch= 
- Users:
  - =system:apiserver=
  - =system:kube-scheduler=
  - =system:kube-controller-manager=
  - =system:node:.*=
- Objects: 
  - =configmaps=, =nodes=, =pods=, =namespaces=, =serviceaccounts=, =rolebindings=,
    =resourcequotas=, =clusterroles=, =secrets=, =clusterrolebindings=, =roles=,
    =certificatesigningrequests=
** CoreDNS watching namespaces 
- Verb: =watch=
- Users: =system:serviceaccount:kube-system:coredns=
- Objects: =namespaces=
** CNI watching nodes
- Verb: =watch=
- Users: =system:serviceaccount:kube-system:kube-flannel=
- Objects: =nodes=
** Kube-proxy watching nodes
- Verb: =watch=
- Users: =system:serviceaccount:kube-system:kube-proxy=
- Objects: =nodes=
** Nodes getting their own status
Nodes poll their own status every ten seconds.
- Verb: =get=
- Users: =system:node:.*=, groups =["system:nodes","system:authenticated"]=
- Objects: =/api/v1/nodes/{the same node}=
** Nodes patching their status to update conditions
Nodes update their status (e.g., MemoryPressure, DiskPressure, PIDPressure) by patching their own status
every five minutes.
- Verb: =patch=
- Users: =system:node:.*=, groups =["system:nodes","system:authenticated"]=
- Objects: =/api/v1/nodes/{the same node}=
** Nodes creating a token for the CNI
Each node independently creates a token for the CNI to use. It expires in an hour.
This token is re-created every 49 minutes (weird, but that's what the logs show).
- Verb: =create=
- Users: =system:node:.*=, groups =["system:nodes","system:authenticated"]=
- Objects: =/api/v1/namespaces/kube-flannel/serviceaccounts/flannel/token=
** Nodes creating a token for the Kubelet
Each node independently creates a token for the Kubelet to use. It expires in an hour.
Just like the CNI token, this token is re-created every 49 minutes.
- Verb: =create=
- Users: =system:node:.*=, groups =["system:nodes","system:authenticated"]=
- Objects: =/api/v1/namespaces/kube-system/serviceaccounts/kubelet/token=
** Master node creates a token for CoreDNS
The master node creates a token for CoreDNS to use.
This token expires in a hour, and is re-created at unpredictable intervals before it expires.
- Verb: =create=
- Users: =system:node:kubeadm-master=
- Objects: =/api/v1/namespaces/kube-system/serviceaccounts/coredns/token=
** Kube-controller-manager getting and creating tokens for GC and RQ controllers
The =kube-controller-manager= gets every less than an hour the serviceaccounts
=/api/v1/namespaces/kube-system/serviceaccounts/generic-garbage-collector= and
=/api/v1/namespaces/kube-system/serviceaccounts/resourcequota-controller=.
It then creates tokens for them, which expire in an hour.
*** 1
- Verb: =get=
- Users: =system:kube-controller-manager=, groups =system:authenticated=
- Objects: =/api/v1/namespaces/kube-system/serviceaccounts/generic-garbage-collector=
*** 2
- Verb: =get=
- Users: =system:kube-controller-manager=, groups =system:authenticated=
- Objects: =/api/v1/namespaces/kube-system/serviceaccounts/resourcequota-controller=
*** 3
- Verb: =create=
- Users: =system:kube-controller-manager=, groups =system:authenticated=
- Objects: =/api/v1/namespaces/kube-system/serviceaccounts/generic-garbage-collector/token=
*** 4
- Verb: =create=
- Users: =system:kube-controller-manager=, groups =system:authenticated=
- Objects: =/api/v1/namespaces/kube-system/serviceaccounts/resourcequota-controller/token=
  
* Log setups 
# :PROPERTIES:
# :header-args:shell: :var TERM=dumb
# :header-args:shell: :var EMACS=1
# :header-args: :prologue "exec 2>&1"
# :header-args: :epilogue ":"
# :header-args: :exports code
# :header-args: :results type code
# :END:

** Namespace log =N1= - Simple namespace creation and deletion
- Create a namespace:
  #+BEGIN_SRC shell 
  kubectl create namespace rising
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  namespace/rising created
  #+end_src

- List the namespaces:
  #+BEGIN_SRC shell 
  kubectl get namespaces
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  NAME              STATUS   AGE
  default           Active   107d
  kube-flannel      Active   107d
  kube-node-lease   Active   107d
  kube-public       Active   107d
  kube-system       Active   107d
  limited           Active   107d
  my-namespace      Active   28d
  rising            Active   10s
  rising2           Active   71m
  #+end_src
  
- Get the namespace using =-o yaml=:
  #+BEGIN_SRC shell
  kubectl get namespace rising -o yaml
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  apiVersion: v1
  kind: Namespace
  metadata:
    creationTimestamp: "2024-06-05T12:46:46Z"
    labels:
      kubernetes.io/metadata.name: rising
    name: rising
    resourceVersion: "3274921"
    uid: c7c2284a-f438-403e-bf6b-ce389d5c779c
  spec:
    finalizers:
    - kubernetes
  status:
    phase: Active
  #+end_src
  
- Describe the namespace:
  #+BEGIN_SRC shell
  kubectl describe namespace rising
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  Name:         rising
  Labels:       kubernetes.io/metadata.name=rising
  Annotations:  <none>
  Status:       Active

  No resource quota.

  No LimitRange resource.
  #+end_src

- Delete the namespace:
  #+BEGIN_SRC shell
  kubectl delete namespace rising
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  namespace "rising" deleted
  #+end_src

** Namespace log =N2= - Namespace with resource quotas
- *Prerequisite*: recreate the =rising= namespace:
   #+BEGIN_SRC shell
   kubectl create namespace rising
   #+END_SRC

   #+RESULTS:
   #+begin_src shell
   Error from server (AlreadyExists): namespaces "rising" already exists
   #+end_src

- Create a ResourceQuota for the namespace:
   #+BEGIN_SRC shell
   cat <<EOF | kubectl apply -f -
   apiVersion: v1
   kind: ResourceQuota
   metadata:
     name: rising-quota 
   spec:
     hard:
       pods: "1"
       requests.cpu: "1"
       requests.memory: 1Gi
       limits.cpu: "2"
       limits.memory: 2Gi
   EOF
   #+END_SRC

   #+RESULTS:
   #+begin_src shell
   resourcequota/rising-quota created
   #+end_src

- Inspect the ResourceQuota:
  #+BEGIN_SRC shell
  kubectl -n rising describe resourcequota rising-quota
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  Name:            rising-quota
  Namespace:       rising
  Resource         Used  Hard
  --------         ----  ----
  limits.cpu       0     2
  limits.memory    0     2Gi
  pods             0     1
  requests.cpu     0     1
  requests.memory  0     1Gi
  #+end_src

- Create a Pod that will exceed the quota:
  #+BEGIN_SRC shell
  cat <<EOF | kubectl apply -f -
  apiVersion: v1
  kind: Pod
  metadata:
    name: over-quota-pod
    namespace: rising
  spec:
    containers:
    - name: over-quota-container
      image: nginx
      resources:
        requests:
          cpu: "1"
          memory: 1.5Gi
        limits:
          cpu: "2"
          memory: 2Gi
      command: ["sh", "-c", "echo Hello, Kubernetes! && sleep 3600"]
  EOF
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  Error from server (Forbidden): error when creating "STDIN": pods "over-quota-pod" is forbidden: exceeded quota: rising-quota, requested: requests.memory=1536Mi, used: requests.memory=0, limited: requests.memory=1Gi
  #+end_src

- Now create a Pod that will respect the quota:
  #+BEGIN_SRC shell
  cat <<EOF | kubectl apply -f -
  apiVersion: v1
  kind: Pod
  metadata:
    name: within-quota-pod
    namespace: rising
  spec:
    containers:
    - name: within-quota-container
      image: nginx
      resources:
        requests:
          cpu: "1"
          memory: 1Gi
        limits:
          cpu: "2"
          memory: 2Gi
      command: ["sh", "-c", "echo Hello, Kubernetes! && sleep 3600"]
  EOF
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  pod/within-quota-pod created
  #+end_src

- Run a further Pod, it will fail:
  #+BEGIN_SRC shell
  kubectl -n rising run --image=nginx nginx
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  Error from server (Forbidden): pods "nginx" is forbidden: failed quota: rising-quota: must specify limits.cpu for: nginx; limits.memory for: nginx; requests.cpu for: nginx; requests.memory for: nginx
  #+end_src
  
- Clean everything up, one pod will fail because it was never created:
  #+BEGIN_SRC shell
    kubectl -n rising delete pod over-quota-pod
    kubectl -n rising delete pod within-quota-pod
    kubectl delete resourcequota rising-quota
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  Error from server (NotFound): pods "over-quota-pod" not found
  pod "within-quota-pod" deleted
  resourcequota "rising-quota" deleted
  #+end_src

** Pod log =P1= - Simple Pod creation and inspection
- Create a pod:
  #+BEGIN_SRC shell 
    cat <<EOF | kubectl apply -f -
    apiVersion: v1
    kind: Pod
    metadata:
      name: rising-pod
      namespace: rising
    spec:
      containers:
      - name: first-container 
        image: nginx
      - name: second-container
        image: alpine 
        command: ["sh", "-c", "echo Hello, Kubernetes! && sleep 3600"]
    EOF
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  pod/rising-pod created
  #+end_src

- Inspect the Pod:
  #+BEGIN_SRC shell
  kubectl -n rising describe pod rising-pod
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  Name:             rising-pod
  Namespace:        rising
  Priority:         0
  Service Account:  default
  Node:             kubeadm-worker1/192.168.38.11
  Start Time:       Wed, 29 May 2024 08:41:47 +0200
  Labels:           <none>
  Annotations:      <none>
  Status:           Pending
  IP:               
  IPs:              <none>
  Containers:
    first-container:
      Container ID:   
      Image:          nginx
      Image ID:       
      Port:           <none>
      Host Port:      <none>
      State:          Waiting
        Reason:       ContainerCreating
      Ready:          False
      Restart Count:  0
      Environment:    <none>
      Mounts:
        /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-gjxhl (ro)
    second-container:
      Container ID:  
      Image:         alpine
      Image ID:      
      Port:          <none>
      Host Port:     <none>
      Command:
        sh
        -c
        echo Hello, Kubernetes! && sleep 3600
      State:          Waiting
        Reason:       ContainerCreating
      Ready:          False
      Restart Count:  0
      Environment:    <none>
      Mounts:
        /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-gjxhl (ro)
  Conditions:
    Type              Status
    Initialized       True 
    Ready             False 
    ContainersReady   False 
    PodScheduled      True 
  Volumes:
    kube-api-access-gjxhl:
      Type:                    Projected (a volume that contains injected data from multiple sources)
      TokenExpirationSeconds:  3607
      ConfigMapName:           kube-root-ca.crt
      ConfigMapOptional:       <nil>
      DownwardAPI:             true
  QoS Class:                   BestEffort
  Node-Selectors:              <none>
  Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                               node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
  Events:
    Type    Reason     Age   From               Message
    ----    ------     ----  ----               -------
    Normal  Scheduled  4s    default-scheduler  Successfully assigned rising/rising-pod to kubeadm-worker1
    Normal  Pulling    4s    kubelet            Pulling image "nginx"
  #+end_src

- Patch the Pod and try to add a third container, this will fail:
  #+BEGIN_SRC shell
  kubectl -n rising patch pod rising-pod --type='json' -p='[{"op": "add", "path": "/spec/containers/1", "value": {"name": "third-container", "image": "nginx"}}]'
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  The Pod "rising-pod" is invalid: spec.containers: Forbidden: pod updates may not add or remove containers
  #+end_src

- Get the pod log:
  #+BEGIN_SRC shell
  kubectl -n rising logs rising-pod -c second-container
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  Hello, Kubernetes!
  #+end_src

- Execute commands in the second containers, the first will complain about the shell, the second will work:
  #+BEGIN_SRC shell
  kubectl -n rising exec -t rising-pod -c second-container -- /bin/bash -c "echo Hello again, Kubernetes!"
  kubectl -n rising exec -t rising-pod -c second-container -- /bin/sh -c "echo Hello again, Kubernetes!"
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  error: Internal error occurred: error executing command in container: failed to exec in container: failed to start exec "fc242965197c3ac44aaeba0cf180d08276c904721d5fcc549f8932e6125dab1b": OCI runtime exec failed: exec failed: unable to start container process: exec: "/bin/bash": stat /bin/bash: no such file or directory: unknown
  Hello again, Kubernetes!
  #+end_src

- Delete the pod:
  #+BEGIN_SRC shell
  kubectl -n rising delete pod rising-pod
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  pod "rising-pod" deleted
  #+end_src
  
** Pod log =P2= - Image download
- *Prerequisite*: run the following helper script to wipe the image cache on all nodes:

  #+BEGIN_SRC shell :results type verbatim
    for node in $(kubectl get nodes -o jsonpath='{.items[*].metadata.name}'); do
      echo "Pruning images on $node"
      ssh -F ssh/cluster-setup $node "sudo crictl rmi --prune"
    done
  #+END_SRC
  
  #+RESULTS:
#+begin_src shell
Pruning images on kubeadm-master
Pruning images on kubeadm-worker1
Deleted: registry.k8s.io/pause:3.6
Deleted: docker.io/library/busybox:latest
Deleted: docker.io/library/alpine:latest
Deleted: docker.io/library/nginx:latest
Pruning images on kubeadm-worker2
#+end_src

- Create a Pod with a container that uses a non-existent image:
  #+BEGIN_SRC shell
  cat <<EOF | kubectl apply -f -
  apiVersion: v1
  kind: Pod
  metadata:
    name: image-pod
    namespace: rising
  spec:
    containers:
    - name: image-container
      image: www.fbk.eu/non-existent-image
      command: ["sh", "-c", "echo Hello, Kubernetes! && sleep 3600"]
  EOF
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  pod/image-pod created
  #+end_src

- Get the pod log:
  #+BEGIN_SRC shell
  kubectl -n rising logs image-pod -c image-container
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  Error from server (BadRequest): container "image-container" in pod "image-pod" is waiting to start: ContainerCreating
  #+end_src

- Get the events that led to the failure:
  #+BEGIN_SRC shell :results type verbatim
  kubectl get events -n rising --sort-by='.metadata.creationTimestamp' --selector 'involvedObject.name=image-pod'
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  21s         Normal    Scheduled                pod/image-pod    Successfully assigned rising/image-pod to kubeadm-worker1
  9s          Warning   FailedCreatePodSandBox   pod/image-pod    Failed to create pod sandbox: rpc error: code = Unknown desc = failed to get sandbox image "registry.k8s.io/pause:3.6": failed to pull image "registry.k8s.io/pause:3.6": failed to pull and unpack image "registry.k8s.io/pause:3.6": failed to copy: httpReadSeeker: failed open: failed to do request: Get "https://prod-registry-k8s-io-eu-central-1.s3.dualstack.eu-central-1.amazonaws.com/containers/images/sha256:6270bb605e12e581514ada5fd5b3216f727db55dc87d5889c790e4c760683fee": dial tcp: lookup prod-registry-k8s-io-eu-central-1.s3.dualstack.eu-central-1.amazonaws.com on 127.0.0.53:53: read udp 127.0.0.1:38875->127.0.0.53:53: i/o timeout
  #+end_src

- Delete the pod:
  #+BEGIN_SRC shell
  kubectl -n rising delete pod image-pod
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  pod "image-pod" deleted
  #+end_src
  
- Create a pod with an image that will surely not be in cache:
  #+BEGIN_SRC shell
    cat <<EOF | kubectl apply -f -
    apiVersion: v1
    kind: Pod
    metadata:
      name: image-pod
      namespace: rising
    spec:
      containers:
      - name: image-container
        image: busybox
        command: ["sh", "-c", "echo Hello, Kubernetes! && sleep 3600"]
    EOF
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  pod/image-pod created
  #+end_src

- Wait for the Pod to be downloaded and monitor the events:
  #+BEGIN_SRC shell
  kubectl wait --for=condition=Ready pod/image-pod -n rising
  kubectl get events -n rising --sort-by='.metadata.creationTimestamp'
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  pod/image-pod condition met
  LAST SEEN   TYPE     REASON      OBJECT          MESSAGE
  5s          Normal   Scheduled   pod/image-pod   Successfully assigned rising/image-pod to kubeadm-worker1
  4s          Normal   Pulling     pod/image-pod   Pulling image "busybox"
  1s          Normal   Pulled      pod/image-pod   Successfully pulled image "busybox" in 3.598s (3.598s including waiting)
  1s          Normal   Created     pod/image-pod   Created container image-container
  1s          Normal   Started     pod/image-pod   Started container image-container
  #+end_src

- Delete the pod:
  #+BEGIN_SRC shell
  kubectl -n rising delete pod image-pod
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  pod "image-pod" deleted
  #+end_src

** ConfigMap =C1= - Create a ConfigMap and use it in a Pod, then delete it
- Create a ConfigMap:
  #+BEGIN_SRC shell
  cat <<EOF | kubectl apply -f -
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: my-config
    namespace: rising
  data:
    status: "decent" 
  EOF
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  configmap/my-config created
  #+end_src

- Get the configmap
  #+BEGIN_SRC shell
  kubectl -n rising get configmap my-config -o yaml
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  apiVersion: v1
  data:
    status: decent
  kind: ConfigMap
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","data":{"status":"decent"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"my-config","namespace":"rising"}}
    creationTimestamp: "2024-05-29T08:24:20Z"
    name: my-config
    namespace: rising
    resourceVersion: "2345205"
    uid: 96f6a9d4-357e-4d79-a887-9ebd02b7be74
  #+end_src

- Deploy a Pod that uses the ConfigMap:
  #+BEGIN_SRC shell
  cat <<EOF | kubectl apply -f -
  apiVersion: v1
  kind: Pod
  metadata:
    name: config-pod
    namespace: rising
  spec:
    containers:
    - name: config-container
      image: alpine
      command: ["sh", "-c", 'echo Status is \$STATUS && sleep 3600']
      env:
      - name: STATUS
        valueFrom:
          configMapKeyRef:
            name: my-config
            key: status
  EOF
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  pod/config-pod created
  #+end_src

- Access the logs of the Pod:
  #+BEGIN_SRC shell
    kubectl wait --for=condition=Ready pod/config-pod -n rising
    kubectl -n rising logs config-pod -c config-container
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  pod/config-pod condition met
  Status is decent
  #+end_src

- Clean everything up:
  #+BEGIN_SRC shell
  kubectl -n rising delete pod config-pod
  kubectl -n rising delete configmap my-config
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  pod "config-pod" deleted
  configmap "my-config" deleted
  #+end_src

** Secret =S1= - Create a Secret and use it as environment in a Pod, then delete it
- Create a secret
  #+BEGIN_SRC shell
  cat <<EOF | kubectl apply -f -
  apiVersion: v1
  kind: Secret
  metadata:
    name: my-secret
    namespace: rising
  type: Opaque
  data:
    username: $(echo -n "admin" | base64)
    password: $(echo -n "password" | base64)
  EOF
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  secret/my-secret created
  #+end_src

- Inspect the secret:
  #+BEGIN_SRC shell
  kubectl -n rising get secret my-secret -o yaml
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  apiVersion: v1
  data:
    password: cGFzc3dvcmQ=
    username: YWRtaW4=
  kind: Secret
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","data":{"password":"cGFzc3dvcmQ=","username":"YWRtaW4="},"kind":"Secret","metadata":{"annotations":{},"name":"my-secret","namespace":"rising"},"type":"Opaque"}
    creationTimestamp: "2024-05-29T08:25:11Z"
    name: my-secret
    namespace: rising
    resourceVersion: "2345300"
    uid: b35c1aee-de5d-4fa5-b755-84e6fc9af764
  type: Opaque
  #+end_src

- Attach the secret to a Pod:
  #+BEGIN_SRC shell
    cat <<EOF | kubectl apply -f -
    apiVersion: v1
    kind: Pod
    metadata:
      name: secret-pod
      namespace: rising
    spec:
      containers:
      - name: secret-container
        image: alpine
        command: ["sh", "-c", 'echo Username is \$USERNAME && echo Password is \$PASSWORD && sleep 3600']
        env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: password    
    EOF
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  pod/secret-pod created
  #+end_src

- Inspect the Pod:
  #+BEGIN_SRC shell
  kubectl -n rising describe pod secret-pod
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  Name:             secret-pod
  Namespace:        rising
  Priority:         0
  Service Account:  default
  Node:             kubeadm-worker1/192.168.38.11
  Start Time:       Wed, 29 May 2024 10:25:19 +0200
  Labels:           <none>
  Annotations:      <none>
  Status:           Running
  IP:               10.244.1.51
  IPs:
    IP:  10.244.1.51
  Containers:
    secret-container:
      Container ID:  containerd://74f7f4f98c4f56da40642ea5924f40aa9dd0b540639a64a25e08f288891caa21
      Image:         alpine
      Image ID:      docker.io/library/alpine@sha256:77726ef6b57ddf65bb551896826ec38bc3e53f75cdde31354fbffb4f25238ebd
      Port:          <none>
      Host Port:     <none>
      Command:
        sh
        -c
        echo Username is $USERNAME && echo Password is $PASSWORD && sleep 3600
      State:          Running
        Started:      Wed, 29 May 2024 10:25:21 +0200
      Ready:          True
      Restart Count:  0
      Environment:
        USERNAME:  <set to the key 'username' in secret 'my-secret'>  Optional: false
        PASSWORD:  <set to the key 'password' in secret 'my-secret'>  Optional: false
      Mounts:
        /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-jfmbf (ro)
  Conditions:
    Type              Status
    Initialized       True 
    Ready             True 
    ContainersReady   True 
    PodScheduled      True 
  Volumes:
    kube-api-access-jfmbf:
      Type:                    Projected (a volume that contains injected data from multiple sources)
      TokenExpirationSeconds:  3607
      ConfigMapName:           kube-root-ca.crt
      ConfigMapOptional:       <nil>
      DownwardAPI:             true
  QoS Class:                   BestEffort
  Node-Selectors:              <none>
  Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                               node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
  Events:
    Type    Reason     Age   From               Message
    ----    ------     ----  ----               -------
    Normal  Scheduled  5s    default-scheduler  Successfully assigned rising/secret-pod to kubeadm-worker1
    Normal  Pulling    4s    kubelet            Pulling image "alpine"
    Normal  Pulled     3s    kubelet            Successfully pulled image "alpine" in 967ms (967ms including waiting)
    Normal  Created    3s    kubelet            Created container secret-container
    Normal  Started    3s    kubelet            Started container secret-container
  #+end_src

- Access the logs of the Pod:
  #+BEGIN_SRC shell
    kubectl wait --for=condition=Ready pod/secret-pod -n rising
    kubectl -n rising logs secret-pod -c secret-container
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  pod/secret-pod condition met
  Username is admin
  Password is password
  #+end_src

- Clean everything up:
  #+BEGIN_SRC shell
  kubectl -n rising delete pod secret-pod
  kubectl -n rising delete secret my-secret
  #+END_SRC
  
  #+RESULTS:
  #+begin_src shell
  pod "secret-pod" deleted
  secret "my-secret" deleted
  #+end_src
** Secret =S2= - Create a Secret and mount it in a Pod 
- Create a secret
  #+BEGIN_SRC shell
  cat <<EOF | kubectl apply -f -
  apiVersion: v1
  kind: Secret
  metadata:
    name: my-secret-2
    namespace: rising
  type: Opaque
  data:
    username: $(echo -n "admin" | base64)
    password: $(echo -n "password" | base64)
  EOF
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  secret/my-secret-2 created
  #+end_src

- Create a Pod, but now, mount the secret as a volume:
  #+BEGIN_SRC shell
    cat <<EOF | kubectl apply -f -
    apiVersion: v1
    kind: Pod
    metadata:
      name: secret-pod-2
      namespace: rising
    spec:
      containers:
      - name: secret-container-2
        image: alpine
        command: ["sh", "-c", 'echo Username is \$USERNAME && echo Password is \$PASSWORD && sleep 3600']
        volumeMounts:
        - name: secret-volume
          mountPath: /etc/secret
      volumes:
      - name: secret-volume
        secret:
          secretName: my-secret-2
    EOF
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  pod/secret-pod-2 created
  #+end_src

- Inspect the Pod:
  #+BEGIN_SRC shell
  kubectl -n rising describe pod secret-pod-2
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  Name:             secret-pod-2
  Namespace:        rising
  Priority:         0
  Service Account:  default
  Node:             kubeadm-worker1/192.168.38.11
  Start Time:       Thu, 13 Jun 2024 17:10:20 +0200
  Labels:           <none>
  Annotations:      <none>
  Status:           Running
  IP:               10.244.1.68
  IPs:
    IP:  10.244.1.68
  Containers:
    secret-container-2:
      Container ID:  containerd://5fe421fbcca0caaed1008c0d1ef913f6dfd7b45c9bfa7cadf7e92f2ce8dadb21
      Image:         alpine
      Image ID:      docker.io/library/alpine@sha256:77726ef6b57ddf65bb551896826ec38bc3e53f75cdde31354fbffb4f25238ebd
      Port:          <none>
      Host Port:     <none>
      Command:
        sh
        -c
        echo Username is $USERNAME && echo Password is $PASSWORD && sleep 3600
      State:          Running
        Started:      Thu, 13 Jun 2024 17:10:22 +0200
      Ready:          True
      Restart Count:  0
      Environment:    <none>
      Mounts:
        /etc/secret from secret-volume (rw)
        /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-ghkd4 (ro)
  Conditions:
    Type              Status
    Initialized       True 
    Ready             True 
    ContainersReady   True 
    PodScheduled      True 
  Volumes:
    secret-volume:
      Type:        Secret (a volume populated by a Secret)
      SecretName:  my-secret-2
      Optional:    false
    kube-api-access-ghkd4:
      Type:                    Projected (a volume that contains injected data from multiple sources)
      TokenExpirationSeconds:  3607
      ConfigMapName:           kube-root-ca.crt
      ConfigMapOptional:       <nil>
      DownwardAPI:             true
  QoS Class:                   BestEffort
  Node-Selectors:              <none>
  Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                               node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
  Events:
    Type    Reason     Age   From               Message
    ----    ------     ----  ----               -------
    Normal  Scheduled  5s    default-scheduler  Successfully assigned rising/secret-pod-2 to kubeadm-worker1
    Normal  Pulling    4s    kubelet            Pulling image "alpine"
    Normal  Pulled     3s    kubelet            Successfully pulled image "alpine" in 963ms (963ms including waiting)
    Normal  Created    3s    kubelet            Created container secret-container-2
    Normal  Started    3s    kubelet            Started container secret-container-2
  #+end_src

- Access the Secret from the Pod:
  #+BEGIN_SRC shell
  kubectl wait --for=condition=Ready pod/secret-pod-2 -n rising
  kubectl -n rising exec secret-pod-2 -- cat /etc/secret/username
  echo
  kubectl -n rising exec secret-pod-2 -- cat /etc/secret/password
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  pod/secret-pod-2 condition met
  admin
  password
  #+end_src

- Clean everything up:
  #+BEGIN_SRC shell
  kubectl -n rising delete pod secret-pod-2
  kubectl -n rising delete secret my-secret-2
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  pod "secret-pod-2" deleted
  secret "my-secret-2" deleted
  #+end_src
  
** Node log =NO1= - Node inspection
- Assess the available nodes in the cluster:

#+BEGIN_SRC shell
kubectl get nodes
#+END_SRC

#+RESULTS:
#+begin_src shell
NAME              STATUS   ROLES           AGE    VERSION
kubeadm-master    Ready    control-plane   101d   v1.28.6
kubeadm-worker1   Ready    <none>          101d   v1.28.6
kubeadm-worker2   Ready    <none>          36d    v1.28.6
#+end_src

- Inspect one of the nodes:
#+BEGIN_SRC shell
kubectl describe node kubeadm-worker1
#+END_SRC

#+RESULTS:
#+begin_src shell
  Name:               kubeadm-worker1
  Roles:              <none>
  Labels:             beta.kubernetes.io/arch=amd64
                      beta.kubernetes.io/os=linux
                      kubernetes.io/arch=amd64
                      kubernetes.io/hostname=kubeadm-worker1
                      kubernetes.io/os=linux
  Annotations:        flannel.alpha.coreos.com/backend-data: {"VNI":1,"VtepMAC":"c6:ae:25:8b:09:38"}
                      flannel.alpha.coreos.com/backend-type: vxlan
                      flannel.alpha.coreos.com/kube-subnet-manager: true
                      flannel.alpha.coreos.com/public-ip: 10.231.0.125
                      kubeadm.alpha.kubernetes.io/cri-socket: unix:///var/run/containerd/containerd.sock
                      node.alpha.kubernetes.io/ttl: 0
                      volumes.kubernetes.io/controller-managed-attach-detach: true
  CreationTimestamp:  Mon, 19 Feb 2024 09:51:17 +0100
  Taints:             <none>
  Unschedulable:      false
  Lease:
    HolderIdentity:  kubeadm-worker1
    AcquireTime:     <unset>
    RenewTime:       Thu, 30 May 2024 13:22:16 +0200
  Conditions:
    Type                 Status  LastHeartbeatTime                 LastTransitionTime                Reason                       Message
    ----                 ------  -----------------                 ------------------                ------                       -------
    NetworkUnavailable   False   Tue, 21 May 2024 09:50:32 +0200   Tue, 21 May 2024 09:50:32 +0200   FlannelIsUp                  Flannel is running on this node
    MemoryPressure       False   Thu, 30 May 2024 13:19:46 +0200   Tue, 30 Apr 2024 09:20:41 +0200   KubeletHasSufficientMemory   kubelet has sufficient memory available
    DiskPressure         False   Thu, 30 May 2024 13:19:46 +0200   Wed, 22 May 2024 15:09:08 +0200   KubeletHasNoDiskPressure     kubelet has no disk pressure
    PIDPressure          False   Thu, 30 May 2024 13:19:46 +0200   Tue, 30 Apr 2024 09:20:41 +0200   KubeletHasSufficientPID      kubelet has sufficient PID available
    Ready                True    Thu, 30 May 2024 13:19:46 +0200   Wed, 08 May 2024 11:24:35 +0200   KubeletReady                 kubelet is posting ready status. AppArmor enabled
  Addresses:
    InternalIP:  192.168.38.11
    Hostname:    kubeadm-worker1
  Capacity:
    cpu:                4
    ephemeral-storage:  20134592Ki
    hugepages-2Mi:      0
    memory:             7395772Ki
    pods:               110
  Allocatable:
    cpu:                4
    ephemeral-storage:  18556039957
    hugepages-2Mi:      0
    memory:             7293372Ki
    pods:               110
  System Info:
    Machine ID:                 41479085bc0642d3b8488951778a732d
    System UUID:                41479085-bc06-42d3-b848-8951778a732d
    Boot ID:                    3cefe34b-fdb3-4e85-b0a3-0357c52fbcd5
    Kernel Version:             5.15.0-107-generic
    OS Image:                   Ubuntu 22.04.4 LTS
    Operating System:           linux
    Architecture:               amd64
    Container Runtime Version:  containerd://1.6.31
    Kubelet Version:            v1.28.6
    Kube-Proxy Version:         v1.28.6
  PodCIDR:                      10.244.1.0/24
  PodCIDRs:                     10.244.1.0/24
  Non-terminated Pods:          (2 in total)
    Namespace                   Name                     CPU Requests  CPU Limits  Memory Requests  Memory Limits  Age
    ---------                   ----                     ------------  ----------  ---------------  -------------  ---
    kube-flannel                kube-flannel-ds-h64vt    100m (2%)     0 (0%)      50Mi (0%)        0 (0%)         101d
    kube-system                 kube-proxy-r85g2         0 (0%)        0 (0%)      0 (0%)           0 (0%)         101d
  Allocated resources:
    (Total limits may be over 100 percent, i.e., overcommitted.)
    Resource           Requests   Limits
    --------           --------   ------
    cpu                100m (2%)  0 (0%)
    memory             50Mi (0%)  0 (0%)
    ephemeral-storage  0 (0%)     0 (0%)
    hugepages-2Mi      0 (0%)     0 (0%)
    Events:              <none>
#+end_src

** Certificate log =CSR1= - Create a CertificateSigningRequest and approve it
:PROPERTIES:
:header-args+: :session csr1
:END:

- Note: an helper script is available in =scripts/generate_k8s_user.sh=
  that automates what is done in this section.

- Use openssl to generate a key and a certificate signing request:
  #+BEGIN_SRC bash 
    export TEMPDIR=$(mktemp -d)
    export ORIGINDIR=$(pwd)
    cd $TEMPDIR
    export KUBEUSER=malicious-user
    openssl genpkey -out ${KUBEUSER}.key -algorithm Ed25519
    openssl req -new -key ${KUBEUSER}.key -out ${KUBEUSER}.csr -subj "/CN=${KUBEUSER}/O=rising/O=fbk/"
    echo "Key created, available in ${TEMPDIR} for user ${KUBEUSER}"
  #+END_SRC

  #+RESULTS:
  #+begin_src bash
  Key created, available in /var/folders/gh/9l_dnc_94b3f42yswbpmn0fc0000gn/T/tmp.M7dVzdtOLc for user malicious-user
  #+end_src

- Create a CertificateSigningRequest:
  #+BEGIN_SRC bash 
  cat <<EOF | kubectl apply -f -
  apiVersion: certificates.k8s.io/v1
  kind: CertificateSigningRequest
  metadata:
    name: ${KUBEUSER}
  spec:
    request: $(cat ${KUBEUSER}.csr | base64 | tr -d '\n')
    signerName: kubernetes.io/kube-apiserver-client
    usages:
    - client auth 
  EOF
  #+END_SRC 

  #+RESULTS:
  #+begin_src bash
  certificatesigningrequest.certificates.k8s.io/malicious-user created
  #+end_src

- Deny the CertificateSigningRequest:
  #+BEGIN_SRC bash 
  kubectl certificate deny ${KUBEUSER}
  #+END_SRC

  #+RESULTS:
  #+begin_src bash
  certificatesigningrequest.certificates.k8s.io/malicious-user denied
  #+end_src
  
- Delete the failed CSR and generate a new keypair for a legitimate user:
  #+BEGIN_SRC bash 
  rm ${KUBEUSER}.csr ${KUBEUSER}.key
  kubectl delete csr ${KUBEUSER}
  export KUBEUSER=rising-user
  openssl genpkey -out ${KUBEUSER}.key -algorithm Ed25519
  openssl req -new -key ${KUBEUSER}.key -out ${KUBEUSER}.csr -subj "/CN=${KUBEUSER}/O=rising/O=fbk/"
  echo "Key created, available in ${TEMPDIR} for user ${KUBEUSER}"
  #+END_SRC

  #+RESULTS:
  #+begin_src bash
  certificatesigningrequest.certificates.k8s.io "malicious-user" deleted
  Key created, available in /var/folders/gh/9l_dnc_94b3f42yswbpmn0fc0000gn/T/tmp.M7dVzdtOLc for user rising-user
  #+end_src

- Generate a new CertificateSigningRequest:
  #+BEGIN_SRC bash
  cat <<EOF | kubectl apply -f -
  apiVersion: certificates.k8s.io/v1
  kind: CertificateSigningRequest
  metadata:
    name: ${KUBEUSER}
  spec:
    request: $(cat ${KUBEUSER}.csr | base64 | tr -d '\n')
    signerName: kubernetes.io/kube-apiserver-client
    usages:
    - client auth 
  EOF
  #+END_SRC

  #+RESULTS:
  #+begin_src bash
  certificatesigningrequest.certificates.k8s.io/rising-user created
  #+end_src

- Inspect the status of the CSR:
  #+BEGIN_SRC bash  
  kubectl get csr ${KUBEUSER} -o yaml
  #+END_SRC

  #+RESULTS:
  #+begin_src bash
  apiVersion: certificates.k8s.io/v1
  kind: CertificateSigningRequest
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"certificates.k8s.io/v1","kind":"CertificateSigningRequest","metadata":{"annotations":{},"name":"rising-user"},"spec":{"request":"LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlHME1HZ0NBUUF3TlRFVU1CSUdBMVVFQXd3TGNtbHphVzVuTFhWelpYSXhEekFOQmdOVkJBb01CbkpwYzJsdQpaekVNTUFvR0ExVUVDZ3dEWm1Kck1Db3dCUVlESzJWd0F5RUE0aGo3b3JSdHkwd0pYTjVsTmZNUzJIbmExdHlWCncxMTlFWmRwUURwQTdKcWdBREFGQmdNclpYQURRUUQ4bE53dGtOSTloUXFVNnF2dVFhaVI4NFFpRFNKeGIvNVoKSWZVMEViWUF3Nm0rcXZ1dUhWQ2lxMXRGYkJCTm9vRjNUbTdXOTZjQVZjZkRUNU9abUdvQgotLS0tLUVORCBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0K","signerName":"kubernetes.io/kube-apiserver-client","usages":["client auth"]}}
    creationTimestamp: "2024-05-30T11:26:05Z"
    name: rising-user
    resourceVersion: "2491043"
    uid: a3c4e1b1-7d91-47ea-8098-3b5308cfa7be
  spec:
    groups:
    - system:authenticated
    request: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0KTUlHME1HZ0NBUUF3TlRFVU1CSUdBMVVFQXd3TGNtbHphVzVuTFhWelpYSXhEekFOQmdOVkJBb01CbkpwYzJsdQpaekVNTUFvR0ExVUVDZ3dEWm1Kck1Db3dCUVlESzJWd0F5RUE0aGo3b3JSdHkwd0pYTjVsTmZNUzJIbmExdHlWCncxMTlFWmRwUURwQTdKcWdBREFGQmdNclpYQURRUUQ4bE53dGtOSTloUXFVNnF2dVFhaVI4NFFpRFNKeGIvNVoKSWZVMEViWUF3Nm0rcXZ1dUhWQ2lxMXRGYkJCTm9vRjNUbTdXOTZjQVZjZkRUNU9abUdvQgotLS0tLUVORCBDRVJUSUZJQ0FURSBSRVFVRVNULS0tLS0K
    signerName: kubernetes.io/kube-apiserver-client
    usages:
    - client auth
    username: mfranzil
  status: {}
  #+end_src

- Approve the CertificateSigningRequest:
  #+BEGIN_SRC bash
  kubectl certificate approve ${KUBEUSER}
  #+END_SRC

  #+RESULTS:
  #+begin_src bash
  certificatesigningrequest.certificates.k8s.io/rising-user approved
  #+end_src
  
- Obtain the certificate from the CSR and store it in the folder
  #+BEGIN_SRC bash 
  kubectl get csr ${KUBEUSER} -o jsonpath='{.status.certificate}' | base64 -d > ${KUBEUSER}.crt
  head -n 2 ${KUBEUSER}.crt
  #+END_SRC

  #+RESULTS:
  #+begin_src bash
  -----BEGIN CERTIFICATE-----
  MIICHzCCAQegAwIBAgIRAOgQrahJ0mPtk6Uu2d/HA9owDQYJKoZIhvcNAQELBQAw
  #+end_src
  
- Use the certificate to generate a =.kubeconfig= for the user:
  #+BEGIN_SRC bash 
    cat <<EOF > ${KUBEUSER}.kubeconfig
    apiVersion: v1
    kind: Config
    preferences: {}
    clusters:
    $(kubectl config view --raw --minify --flatten | yq .clusters)
    contexts: []
    users: []
    EOF
    kubectl --kubeconfig ${KUBEUSER}.kubeconfig config set-credentials ${KUBEUSER} --client-certificate=${KUBEUSER}.crt --client-key=${KUBEUSER}.key --embed-certs=true
    kubectl --kubeconfig ${KUBEUSER}.kubeconfig config set-context ${KUBEUSER} --cluster=kubernetes --user=${KUBEUSER} --cluster=risinglab
    kubectl --kubeconfig ${KUBEUSER}.kubeconfig config use-context ${KUBEUSER}
    cp ${KUBEUSER}.kubeconfig ${ORIGINDIR}
  #+END_SRC

  #+RESULTS:
  #+begin_src bash
  User "rising-user" set.
  Context "rising-user" created.
  Switched to context "rising-user".
  #+end_src

** Role log =R1= - Create a Role and bind it to a User 
- *Prerequisite*: complete =CSR1= and obtain the credentials for the user. Make sure
  they are available as =rising-user.kubeconfig= in the current directory.
  
- Create a Role:
  #+BEGIN_SRC shell
  cat <<EOF | kubectl apply -f -
  apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: rising-reader
    namespace: rising
  rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  EOF
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  role.rbac.authorization.k8s.io/rising-reader created
  #+end_src

- List the roles in the namespace:
  #+BEGIN_SRC shell
  kubectl -n rising get roles
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  NAME            CREATED AT
  rising-reader   2024-05-30T11:28:09Z
  #+end_src

- We changed idea: let's also give =get=, =list=, =patch= and =watch= for Secrets:
  #+BEGIN_SRC shell
  kubectl patch role rising-reader -n rising --type='json' -p='[{"op": "add", "path": "/rules/0", "value": {"apiGroups": [""], "resources": ["secrets"], "verbs": ["get", "list", "patch", "watch"]}}]'
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  role.rbac.authorization.k8s.io/rising-reader patched
  #+end_src

- Let's create a RoleBinding and assign it to the user:
  #+BEGIN_SRC shell
  cat <<EOF | kubectl apply -f -
  apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: pod-reader-binding
    namespace: rising
  subjects:
  - kind: User
    name: rising-user
  roleRef:
    kind: Role
    name: rising-reader
    apiGroup: rbac.authorization.k8s.io
  EOF
  #+END_SRC 

  #+RESULTS:
  #+begin_src shell
  rolebinding.rbac.authorization.k8s.io/pod-reader-binding created
  #+end_src

- Test the permissions of the user:
  #+BEGIN_SRC shell
  kubectl --kubeconfig rising-user.kubeconfig get pods -n rising
  kubectl --kubeconfig rising-user.kubeconfig get secrets -n rising
  kubectl --kubeconfig rising-user.kubeconfig delete pod non-existent-pod -n rising  
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  No resources found in rising namespace.
  No resources found in rising namespace.
  Error from server (Forbidden): pods "non-existent-pod" is forbidden: User "rising-user" cannot delete resource "pods" in API group "" in the namespace "rising"
  #+end_src
  
** Role log =R2= - Create a ClusterRole and bind it to a Group
- *Prequisite*: complete =CSR1= and obtain the credentials for the user. Make sure
  they are available as =rising-user.kubeconfig= in the current directory.
- *Prequisite*: complete =R1= and keep the =rising-reader= Role. 

- Create a ClusterRole:
  #+BEGIN_SRC shell
  cat <<EOF | kubectl apply -f -
  apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: cluster-reader
  rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "patch", "watch"]
  EOF
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  clusterrole.rbac.authorization.k8s.io/cluster-reader created
  #+end_src

- Actually, let's straight out replace the ClusterRole with a new one:
  #+BEGIN_SRC shell
  cat <<EOF | kubectl apply -f -
  apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: cluster-reader
  rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]
  EOF
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  clusterrole.rbac.authorization.k8s.io/cluster-reader configured
  #+end_src

- Create a ClusterRoleBinding and assign it to the =fbk= group:
  #+BEGIN_SRC shell
  cat <<EOF | kubectl apply -f -
  apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: cluster-reader-binding
  subjects:
    - kind: Group
      name: fbk
  roleRef:
    kind: ClusterRole
    name: cluster-reader
    apiGroup: rbac.authorization.k8s.io
  EOF
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  clusterrolebinding.rbac.authorization.k8s.io/cluster-reader-binding created
  #+end_src
   
- Test the permissions of the user:
  #+BEGIN_SRC shell
  kubectl --kubeconfig rising-user.kubeconfig get nodes
  kubectl --kubeconfig rising-user.kubeconfig get pods -n rising
  kubectl --kubeconfig rising-user.kubeconfig get configmaps -n rising
  kubectl --kubeconfig rising-user.kubeconfig get pods -n kube-system
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  NAME              STATUS   ROLES           AGE    VERSION
  kubeadm-master    Ready    control-plane   101d   v1.28.6
  kubeadm-worker1   Ready    <none>          101d   v1.28.6
  kubeadm-worker2   Ready    <none>          36d    v1.28.6
  No resources found in rising namespace.
  Error from server (Forbidden): configmaps is forbidden: User "rising-user" cannot list resource "configmaps" in API group "" in the namespace "rising"
  Error from server (Forbidden): pods is forbidden: User "rising-user" cannot list resource "pods" in API group "" in the namespace "kube-system"
  #+end_src
  
- Clean everything up:
  #+BEGIN_SRC shell
  kubectl delete rolebinding pod-reader-binding -n rising
  kubectl delete role rising-reader -n rising
  kubectl delete clusterrolebinding cluster-reader-binding
  kubectl delete clusterrole cluster-reader
  kubectl delete csr rising-user
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  rolebinding.rbac.authorization.k8s.io "pod-reader-binding" deleted
  role.rbac.authorization.k8s.io "rising-reader" deleted
  clusterrolebinding.rbac.authorization.k8s.io "cluster-reader-binding" deleted
  clusterrole.rbac.authorization.k8s.io "cluster-reader" deleted
  certificatesigningrequest.certificates.k8s.io "rising-user" deleted
  #+end_src

** Role log =R3= - Create a ServiceAccount for a long-running Pod and bind it to a Role
- Set up a ServiceAccount:
  #+BEGIN_SRC shell
  cat <<EOF | kubectl apply -f -
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: long-running-sa
    namespace: rising
  EOF
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  serviceaccount/long-running-sa created
  #+end_src

- Create a Role:
  #+BEGIN_SRC shell
  cat <<EOF | kubectl apply -f -
  apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: long-running-role
    namespace: rising
  rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  EOF
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  role.rbac.authorization.k8s.io/long-running-role created
  #+end_src

- Bind the ServiceAccount to the Role:
  #+BEGIN_SRC shell
  cat <<EOF | kubectl apply -f -
  apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: long-running-role-binding
    namespace: rising
  subjects:
  - kind: ServiceAccount
    name: long-running-sa
    namespace: rising
  roleRef:
    kind: Role
    name: long-running-role
    apiGroup: rbac.authorization.k8s.io
  EOF
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  rolebinding.rbac.authorization.k8s.io/long-running-role-binding created
  #+end_src

- Create a Pod that uses the ServiceAccount:
  #+BEGIN_SRC shell
  cat <<EOF | kubectl apply -f -
  apiVersion: v1
  kind: Pod
  metadata:
    name: long-running-pod
    namespace: rising
  spec:
    serviceAccountName: long-running-sa
    containers:
    - name: long-running-container
      image: ubuntu 
      command: ["sh", "-c", "echo Hello, Kubernetes! && sleep 3600"]
  EOF
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  pod/long-running-pod created
  #+end_src

- Inspect the Pod:
  #+BEGIN_SRC shell
  kubectl -n rising describe pod long-running-pod | head -n 10
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  Name:             long-running-pod
  Namespace:        rising
  Priority:         0
  Service Account:  long-running-sa
  Node:             kubeadm-worker1/192.168.38.11
  Start Time:       Fri, 31 May 2024 10:31:49 +0200
  Labels:           <none>
  Annotations:      <none>
  Status:           Running
  IP:               10.244.1.58
  #+end_src

- Try to use the ServiceAccount from inside the Pod:
  #+BEGIN_SRC shell
    kubectl wait --for=condition=Ready pod/long-running-pod -n rising
    kubectl -n rising exec long-running-pod -- sh -c 'apt-get -qq update; apt-get install -yqq curl yq >/dev/null;
    export KUBE_TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token);
    curl -sSk -H "Authorization: Bearer $KUBE_TOKEN" "https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_PORT_443_TCP_PORT/apis/authentication.k8s.io/v1/selfsubjectaccessreviews" > temp.json; jq .message temp.json
    curl -sSk -H "Authorization: Bearer $KUBE_TOKEN" "https://$KUBERNETES_SERVICE_HOST:$KUBERNETES_PORT_443_TCP_PORT/api/v1/namespaces/rising/pods" > temp.json; head -n 5 temp.json'
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  pod/long-running-pod condition met
  "selfsubjectaccessreviews.authentication.k8s.io is forbidden: User \"system:serviceaccount:rising:long-running-sa\" cannot list resource \"selfsubjectaccessreviews\" in API group \"authentication.k8s.io\" at the cluster scope"
  {
    "kind": "PodList",
    "apiVersion": "v1",
    "metadata": {
      "resourceVersion": "2605973"
  #+end_src
  
- Clean everything up:
  #+BEGIN_SRC shell
  kubectl -n rising delete pod long-running-pod
  kubectl -n rising delete role long-running-role
  kubectl -n rising delete rolebinding long-running-role-binding
  kubectl -n rising delete serviceaccount long-running-sa
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  pod "long-running-pod" deleted
  role.rbac.authorization.k8s.io "long-running-role" deleted
  rolebinding.rbac.authorization.k8s.io "long-running-role-binding" deleted
  serviceaccount "long-running-sa" deleted
  #+end_src
  
** Access Review =AR1= - Use can-i to view permissions of self, other users, over different namespaces
- Create a set of ServiceAccounts for the logs (while this
  should not be the case in a real-world scenario, it is done
  since SAs and Users are equivalent once authorized):
  #+BEGIN_SRC shell
  kubectl apply -f - <<EOF
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: alice
    namespace: rising
  ---
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: bob
    namespace: rising
  ---
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: charlie
    namespace: rising
  EOF
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  serviceaccount/alice created
  serviceaccount/bob created
  serviceaccount/charlie created
  #+end_src

- Create tokens for the ServiceAccounts:
  #+BEGIN_SRC shell
  kubectl apply -f - <<EOF
  apiVersion: v1
  kind: Secret
  metadata:
    name: alice-token
    namespace: rising
    annotations:
      kubernetes.io/service-account.name: alice
  type: kubernetes.io/service-account-token
  ---
  apiVersion: v1
  kind: Secret
  metadata:
    name: bob-token
    namespace: rising
    annotations:
      kubernetes.io/service-account.name: bob 
  type: kubernetes.io/service-account-token
  ---
  apiVersion: v1
  kind: Secret
  metadata:
    name: charlie-token
    namespace: rising
    annotations:
      kubernetes.io/service-account.name: charlie
  type: kubernetes.io/service-account-token
  ---
  EOF
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  secret/alice-token created
  secret/bob-token created
  secret/charlie-token created
  #+end_src

- Create two Roles, one for reading Pods and one for reading Secrets:
  #+BEGIN_SRC shell
  kubectl apply -f - <<EOF
  apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: pod-reader
    namespace: rising
  rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
  ---
  apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: secret-reader
    namespace: rising
  rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list"]
  EOF
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  role.rbac.authorization.k8s.io/pod-reader created
  role.rbac.authorization.k8s.io/secret-reader created
  #+end_src

- Bind the ServiceAccounts to the Roles:
  #+BEGIN_SRC shell
  kubectl apply -f - <<EOF
  apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: pod-reader-binding
    namespace: rising
  subjects:
    - kind: ServiceAccount
      name: alice
      namespace: rising
    - kind: ServiceAccount
      name: bob
      namespace: rising
  roleRef:
    kind: Role
    name: pod-reader
    apiGroup: rbac.authorization.k8s.io
  ---
  apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: secret-reader-binding
    namespace: rising
  subjects:
    - kind: ServiceAccount
      name: charlie
      namespace: rising
  roleRef:
    kind: Role
    name: secret-reader
    apiGroup: rbac.authorization.k8s.io
  EOF
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  rolebinding.rbac.authorization.k8s.io/pod-reader-binding created
  rolebinding.rbac.authorization.k8s.io/secret-reader-binding created
  #+end_src

- Obtain credentials for the ServiceAccounts and generate a kubeconfig for them:
  #+BEGIN_SRC shell
  kubectl get secret alice-token -n rising -o jsonpath='{.data.token}' | base64 -d > alice.token
  kubectl get secret bob-token -n rising -o jsonpath='{.data.token}' | base64 -d > bob.token
  kubectl get secret charlie-token -n rising -o jsonpath='{.data.token}' | base64 -d > charlie.token
  cat <<EOF > alice.kubeconfig
  apiVersion: v1
  kind: Config
  preferences: {}
  clusters:
  $(kubectl config view --raw --minify --flatten | yq .clusters)
  contexts: []
  users: []
  EOF
  cp alice.kubeconfig bob.kubeconfig
  cp alice.kubeconfig charlie.kubeconfig
  kubectl --kubeconfig alice.kubeconfig config set-credentials alice --token=$(cat alice.token)
  kubectl --kubeconfig bob.kubeconfig config set-credentials bob --token=$(cat bob.token)
  kubectl --kubeconfig charlie.kubeconfig config set-credentials charlie --token=$(cat charlie.token)
  kubectl --kubeconfig alice.kubeconfig config set-context alice --cluster=kubernetes --user=alice --cluster=risinglab
  kubectl --kubeconfig bob.kubeconfig config set-context bob --cluster=kubernetes --user=bob --cluster=risinglab
  kubectl --kubeconfig charlie.kubeconfig config set-context charlie --cluster=kubernetes --user=charlie --cluster=risinglab
  kubectl --kubeconfig alice.kubeconfig config use-context alice
  kubectl --kubeconfig bob.kubeconfig config use-context bob
  kubectl --kubeconfig charlie.kubeconfig config use-context charlie
  rm alice.token bob.token charlie.token
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  User "alice" set.
  User "bob" set.
  User "charlie" set.
  Context "alice" created.
  Context "bob" created.
  Context "charlie" created.
  Switched to context "alice".
  Switched to context "bob".
  Switched to context "charlie".
  #+end_src

- Check as Alice if she can list Pods and Secrets in the namespace:
  #+BEGIN_SRC shell
  kubectl --kubeconfig alice.kubeconfig auth can-i list pods -n rising
  kubectl --kubeconfig alice.kubeconfig auth can-i list secrets -n rising
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  yes
  no
  #+end_src

- Check as Bob if he can list Pods in the namespaces =rising= and =kube-system=:
  #+BEGIN_SRC shell
  kubectl --kubeconfig bob.kubeconfig auth can-i list pods -n rising
  kubectl --kubeconfig bob.kubeconfig auth can-i list pods -n kube-system
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  yes
  no
  #+end_src

- Check as Charlie if he can list Secrets in the namespace:
  #+BEGIN_SRC shell
  kubectl --kubeconfig charlie.kubeconfig auth can-i list secrets -n rising
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  yes
  #+end_src

- Check as Charlie if he can list nodes:
  #+BEGIN_SRC shell
  kubectl --kubeconfig charlie.kubeconfig auth can-i list nodes
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  Warning: resource 'nodes' is not namespace scoped

  no
  #+end_src

- Check what Charlie can do in the =rising= namespace:
  #+BEGIN_SRC shell
  kubectl --kubeconfig charlie.kubeconfig auth can-i --list -n rising 
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  Resources                                       Non-Resource URLs                      Resource Names   Verbs
  selfsubjectreviews.authentication.k8s.io        []                                     []               [create]
  selfsubjectaccessreviews.authorization.k8s.io   []                                     []               [create]
  selfsubjectrulesreviews.authorization.k8s.io    []                                     []               [create]
  secrets                                         []                                     []               [get list]
                                                  [/.well-known/openid-configuration/]   []               [get]
                                                  [/.well-known/openid-configuration]    []               [get]
                                                  [/api/*]                               []               [get]
                                                  [/api]                                 []               [get]
                                                  [/apis/*]                              []               [get]
                                                  [/apis]                                []               [get]
                                                  [/healthz]                             []               [get]
                                                  [/healthz]                             []               [get]
                                                  [/livez]                               []               [get]
                                                  [/livez]                               []               [get]
                                                  [/openapi/*]                           []               [get]
                                                  [/openapi]                             []               [get]
                                                  [/openid/v1/jwks/]                     []               [get]
                                                  [/openid/v1/jwks]                      []               [get]
                                                  [/readyz]                              []               [get]
                                                  [/readyz]                              []               [get]
                                                  [/version/]                            []               [get]
                                                  [/version/]                            []               [get]
                                                  [/version]                             []               [get]
                                                  [/version]                             []               [get]
  serviceaccounts                                 []                                     [alice]          [impersonate]
  serviceaccounts                                 []                                     [bob]            [impersonate]
  #+end_src
  
** Access Review =AR2= - Use auth whoami to view the current user
- *Prerequisite*: complete =AR1= and obtain the credentials for the users. Make sure
  they are available as =alice.kubeconfig=, =bob.kubeconfig= and =charlie.kubeconfig= in the current directory.

- Check as each of the users who they are: 
  #+BEGIN_SRC shell
  kubectl --kubeconfig alice.kubeconfig auth whoami
  kubectl --kubeconfig bob.kubeconfig auth whoami
  kubectl --kubeconfig charlie.kubeconfig auth whoami
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  ATTRIBUTE   VALUE
  Username    system:serviceaccount:rising:alice
  UID         4d26c60c-0786-43b2-ba36-7a2a0c878e01
  Groups      [system:serviceaccounts system:serviceaccounts:rising system:authenticated]
  ATTRIBUTE   VALUE
  Username    system:serviceaccount:rising:bob
  UID         8e31af98-4542-40a5-b37d-8d7f8c3b31d9
  Groups      [system:serviceaccounts system:serviceaccounts:rising system:authenticated]
  ATTRIBUTE   VALUE
  Username    system:serviceaccount:rising:charlie
  UID         5b50d6c3-fae2-4d06-8277-75e93a5db4ee
  Groups      [system:serviceaccounts system:serviceaccounts:rising system:authenticated]
  #+end_src

** Access Review =AR3= - Impersonating a user
- *Prerequisite*: complete =AR1= and obtain the credentials for the users. Make sure
  they are available as =alice.kubeconfig=, =bob.kubeconfig= and =charlie.kubeconfig= in the current directory.
  
- Augment Charlie's capabilities to let him impersonate ServiceAccounts:
  #+BEGIN_SRC shell
  kubectl apply -f - <<EOF
  apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: impersonator
  rules:
    - apiGroups: [""]
      resources: ["serviceaccounts"]
      verbs: ["impersonate"]
      resourceNames: ["alice", "bob"]
  ---
  apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRoleBinding
  metadata:
    name: impersonator-binding
  subjects:
    - kind: ServiceAccount
      name: charlie
      namespace: rising
  roleRef:
    kind: ClusterRole
    name: impersonator
    apiGroup: rbac.authorization.k8s.io
  EOF
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  clusterrole.rbac.authorization.k8s.io/impersonator created
  clusterrolebinding.rbac.authorization.k8s.io/impersonator-binding created
  #+end_src
  
- Check if Charlie can impersonate any user or SA: 
  #+BEGIN_SRC shell
  kubectl --kubeconfig charlie.kubeconfig auth can-i impersonate users
  kubectl --kubeconfig charlie.kubeconfig auth can-i impersonate serviceaccounts
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  no
  #+end_src

- Let Charlie see if Alice can list Pods in =rising=, and what she can do in =kube-system=:
  #+BEGIN_SRC shell
  kubectl --kubeconfig charlie.kubeconfig auth can-i list pods -n rising --as system:serviceaccount:rising:alice
  kubectl --kubeconfig charlie.kubeconfig auth can-i --list -n kube-system --as system:serviceaccount:rising:alice
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  yes
  Resources                                       Non-Resource URLs                      Resource Names   Verbs
  selfsubjectreviews.authentication.k8s.io        []                                     []               [create]
  selfsubjectaccessreviews.authorization.k8s.io   []                                     []               [create]
  selfsubjectrulesreviews.authorization.k8s.io    []                                     []               [create]
                                                  [/.well-known/openid-configuration/]   []               [get]
                                                  [/.well-known/openid-configuration]    []               [get]
                                                  [/api/*]                               []               [get]
                                                  [/api]                                 []               [get]
                                                  [/apis/*]                              []               [get]
                                                  [/apis]                                []               [get]
                                                  [/healthz]                             []               [get]
                                                  [/healthz]                             []               [get]
                                                  [/livez]                               []               [get]
                                                  [/livez]                               []               [get]
                                                  [/openapi/*]                           []               [get]
                                                  [/openapi]                             []               [get]
                                                  [/openid/v1/jwks/]                     []               [get]
                                                  [/openid/v1/jwks]                      []               [get]
                                                  [/readyz]                              []               [get]
                                                  [/readyz]                              []               [get]
                                                  [/version/]                            []               [get]
                                                  [/version/]                            []               [get]
                                                  [/version]                             []               [get]
                                                  [/version]                             []               [get]
  #+end_src

- As Charlie, let's impersonate Bob and create a Pod in the =rising= namespace, then list Pods:
  #+BEGIN_SRC shell
  kubectl --kubeconfig charlie.kubeconfig --as system:serviceaccount:rising:bob run --image=ubuntu --restart=Never --namespace=rising --command -- sleep 3600
  kubectl --kubeconfig charlie.kubeconfig --as system:serviceaccount:rising:bob get pods -n rising
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  Error from server (Forbidden): pods is forbidden: User "system:serviceaccount:rising:bob" cannot create resource "pods" in API group "" in the namespace "rising"
  No resources found in rising namespace.
  #+end_src

- As Charlie, let's impersonate Alice and try to list nodes:
  #+BEGIN_SRC shell
  kubectl --kubeconfig charlie.kubeconfig --as system:serviceaccount:rising:alice get nodes
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  Error from server (Forbidden): nodes is forbidden: User "system:serviceaccount:rising:alice" cannot list resource "nodes" in API group "" at the cluster scope
  #+end_src

- Clean everything up:
  #+BEGIN_SRC shell
    kubectl delete clusterrolebinding impersonator-binding
    kubectl delete clusterrole impersonator
    kubectl delete rolebinding pod-reader-binding -n rising
    kubectl delete role pod-reader -n rising
    kubectl delete rolebinding secret-reader-binding -n rising
    kubectl delete role secret-reader -n rising
    kubectl delete secret alice-token bob-token charlie-token -n rising
    kubectl delete serviceaccount alice bob charlie -n rising
    rm alice.kubeconfig bob.kubeconfig charlie.kubeconfig
  #+END_SRC

  #+RESULTS:
  #+begin_src shell
  clusterrolebinding.rbac.authorization.k8s.io "impersonator-binding" deleted
  clusterrole.rbac.authorization.k8s.io "impersonator" deleted
  rolebinding.rbac.authorization.k8s.io "pod-reader-binding" deleted
  role.rbac.authorization.k8s.io "pod-reader" deleted
  rolebinding.rbac.authorization.k8s.io "secret-reader-binding" deleted
  role.rbac.authorization.k8s.io "secret-reader" deleted
  secret "alice-token" deleted
  secret "bob-token" deleted
  secret "charlie-token" deleted
  serviceaccount "alice" deleted
  serviceaccount "bob" deleted
  serviceaccount "charlie" deleted
  #+end_src

