#+NAME: Commands used to generate logs
#+AUTHOR: Matteo Franzil, Valentino Armani
#+DATE: 2024-05-28
#+DESCRIPTION: This document contains the commands used to generate the logs for the Audit project
#+PROPERTY: header-args :exports code
#+PROPERTY: header-args :results type verbatim
#+PROPERTY: header-args:shell :prologue "exec 2>&1" :epilogue ":"

# Unused properties
# #+PROPERTY: header-args :eval both
# -*- org-confirm-babel-evaluate: nil -*-

#+LATEX_HEADER: \usepackage{xcolor}
#+SETUPFILE: latex.setup 


* Log setups 
:PROPERTIES:
:END:

** Namespace log =N1= - Simple namespace creation and deletion
- Create a namespace:
  #+BEGIN_SRC shell 
  kubectl create namespace rising
  #+END_SRC

  #+RESULTS:
  : Error from server (AlreadyExists): namespaces "rising" already exists

- Get the namespace:
  #+BEGIN_SRC shell 
  kubectl get namespaces
  #+END_SRC

  #+RESULTS:
  | NAME            | STATUS | AGE |
  | default         | Active | 99d |
  | kube-flannel    | Active | 99d |
  | kube-node-lease | Active | 99d |
  | kube-public     | Active | 99d |
  | kube-system     | Active | 99d |
  | limited         | Active | 99d |
  | my-namespace    | Active | 19d |
  | rising          | Active | 96m |
  
- Describe the namespace:
  #+BEGIN_SRC shell
  kubectl describe namespace rising
  #+END_SRC

  #+RESULTS:
  | Name:        | rising                             |           |
  | Labels:      | kubernetes.io/metadata.name=rising |           |
  | Annotations: | <none>                             |           |
  | Status:      | Active                             |           |
  |              |                                    |           |
  | No           | resource                           | quota.    |
  |              |                                    |           |
  | No           | LimitRange                         | resource. |

- Delete the namespace:
  #+BEGIN_SRC shell
  kubectl delete namespace rising
  #+END_SRC

  #+RESULTS:
  : namespace "rising" deleted

** Namespace log =N2= - Namespace with resource quotas
** Pod log =P1= - Simple Pod creation and inspection
- Create a pod:
  #+BEGIN_SRC shell 
    cat <<EOF | kubectl apply -f -
    apiVersion: v1
    kind: Pod
    metadata:
      name: rising-pod
      namespace: rising
    spec:
      containers:
      - name: first-container 
        image: nginx
      - name: second-container
        image: alpine 
        command: ["sh", "-c", "echo Hello, Kubernetes! && sleep 3600"]
    EOF
  #+END_SRC

  #+RESULTS:
  : pod/rising-pod created

- Inspect the Pod:
  #+BEGIN_SRC shell
  kubectl -n rising describe pod rising-pod
  #+END_SRC

- Patch the Pod and try to add a third container, this will fail:
  #+BEGIN_SRC shell
  kubectl -n rising patch pod rising-pod --type='json' -p='[{"op": "add", "path": "/spec/containers/1", "value": {"name": "third-container", "image": "nginx"}}]'
  #+END_SRC

  #+RESULTS:

- Get the pod log:
  #+BEGIN_SRC shell
  kubectl -n rising logs rising-pod -c second-container
  #+END_SRC

  #+RESULTS:
  | Hello | Kubernetes! |

- Execute commands in the second containers, the first will complain about the shell, the second will work:
  #+BEGIN_SRC shell
  kubectl -n rising exec -t rising-pod -c second-container -- /bin/bash -c "echo Hello again, Kubernetes!"
  kubectl -n rising exec -t rising-pod -c second-container -- /bin/sh -c "echo Hello again, Kubernetes!"
  #+END_SRC

  #+RESULTS:
  | Hello again | Kubernetes! |

- Delete the pod:
  #+BEGIN_SRC shell
  kubectl -n rising delete pod rising-pod
  #+END_SRC

  #+RESULTS:
  : pod "rising-pod" deleted
  
** Pod log =P2= - Image download
*Prerequisites*: run the following helper script to wipe the image cache on all nodes:

#+BEGIN_SRC shell :results type verbatim
  for node in $(kubectl get nodes -o jsonpath='{.items[*].metadata.name}'); do
    echo "Pruning images on $node"
    ssh -F ssh/cluster-setup $node "sudo crictl rmi --prune"
  done
#+END_SRC

#+RESULTS:
: Pruning images on kubeadm-master
: time="2024-05-28T12:49:20Z" level=warning msg="image connect using default endpoints: [unix:///var/run/dockershim.sock unix:///run/containerd/containerd.sock unix:///run/crio/crio.sock unix:///var/run/cri-dockerd.sock]. As the default settings are now deprecated, you should set the endpoint instead."
: time="2024-05-28T12:49:20Z" level=error msg="validate service connection: validate CRI v1 image API for endpoint \"unix:///var/run/dockershim.sock\": rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial unix /var/run/dockershim.sock: connect: no such file or directory\""
: time="2024-05-28T12:49:20Z" level=warning msg="runtime connect using default endpoints: [unix:///var/run/dockershim.sock unix:///run/containerd/containerd.sock unix:///run/crio/crio.sock unix:///var/run/cri-dockerd.sock]. As the default settings are now deprecated, you should set the endpoint instead."
: time="2024-05-28T12:49:20Z" level=error msg="validate service connection: validate CRI v1 runtime API for endpoint \"unix:///var/run/dockershim.sock\": rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial unix /var/run/dockershim.sock: connect: no such file or directory\""
: Pruning images on kubeadm-worker1
: Pruning images on kubeadm-worker2

With the image cache cleared, we can now run the following tests:
- Create a Pod with a container that uses a non-existent image:
  #+BEGIN_SRC shell
  cat <<EOF | kubectl apply -f -
  apiVersion: v1
  kind: Pod
  metadata:
    name: image-pod
    namespace: rising
  spec:
    containers:
    - name: image-container
      image: www.fbk.eu/non-existent-image
      command: ["sh", "-c", "echo Hello, Kubernetes! && sleep 3600"]
  EOF
  #+END_SRC

  #+RESULTS:
  : pod/image-pod created

- Get the pod log:
  #+BEGIN_SRC shell
  kubectl -n rising logs image-pod -c image-container
  #+END_SRC

  #+RESULTS:
  : Error from server (BadRequest): container "image-container" in pod "image-pod" is waiting to start: image can't be pulled

- Get the events that led to the failure:
  #+BEGIN_SRC shell :results type verbatim
  kubectl get events -n rising --sort-by='.metadata.creationTimestamp'
  #+END_SRC

  #+RESULTS:
  #+begin_example
  LAST SEEN   TYPE      REASON                   OBJECT          MESSAGE
  13s         Normal    Scheduled                pod/image-pod   Successfully assigned rising/image-pod to kubeadm-worker1
  12s         Normal    Pulling                  pod/image-pod   Pulling image "www.fbk.eu/non-existent-image"
  11s         Warning   Failed                   pod/image-pod   Failed to pull image "www.fbk.eu/non-existent-image": rpc error: code = NotFound desc = failed to pull and unpack image "www.fbk.eu/non-existent-image:latest": failed to resolve reference "www.fbk.eu/non-existent-image:latest": www.fbk.eu/non-existent-image:latest: not found
  11s         Warning   Failed                   pod/image-pod   Error: ErrImagePull
  10s         Normal    BackOff                  pod/image-pod   Back-off pulling image "www.fbk.eu/non-existent-image"
  10s         Warning   Failed                   pod/image-pod   Error: ImagePullBackOff
  #+end_example

- Delete the pod:
  #+BEGIN_SRC shell
  kubectl -n rising delete pod image-pod
  #+END_SRC

  #+RESULTS:
  : pod "image-pod" deleted
  
- Create a pod with an image that will surely not be in cache:
  #+BEGIN_SRC shell
    cat <<EOF | kubectl apply -f -
    apiVersion: v1
    kind: Pod
    metadata:
      name: image-pod
      namespace: rising
    spec:
      containers:
      - name: image-container
        image: busybox
        command: ["sh", "-c", "echo Hello, Kubernetes! && sleep 3600"]
    EOF
   #+END_SRC

   #+RESULTS:
   : pod/image-pod created

- Wait for the Pod to be downloaded and monitor the events:
  #+BEGIN_SRC shell
  kubectl wait --for=condition=Ready pod/image-pod -n rising
  kubectl get events -n rising --sort-by='.metadata.creationTimestamp'
  #+END_SRC

  #+RESULTS:
  #+begin_example
  pod/image-pod condition met
  LAST SEEN   TYPE      REASON                   OBJECT          MESSAGE
  6s          Normal    Scheduled                pod/image-pod   Successfully assigned rising/image-pod to kubeadm-worker1
  5s          Normal    Pulling                  pod/image-pod   Pulling image "busybox"
  1s          Normal    Pulled                   pod/image-pod   Successfully pulled image "busybox" in 4.047s (4.047s including waiting)
  1s          Normal    Created                  pod/image-pod   Created container image-container
  1s          Normal    Started                  pod/image-pod   Started container image-container
  #+end_example

- Delete the pod:
  #+BEGIN_SRC shell
  kubectl -n rising delete pod image-pod
  #+END_SRC

   #+RESULTS:
   : pod "image-pod" deleted

** ConfigMap =C1= - Create a ConfigMap and use it in a Pod, then delete it
- Create a ConfigMap:
  #+BEGIN_SRC shell
  cat <<EOF | kubectl apply -f -
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: my-config
    namespace: rising
  data:
    status: "decent" 
  EOF
  #+END_SRC

  #+RESULTS:
  : configmap/my-config created

- Get the configmap
  #+BEGIN_SRC shell
  kubectl -n rising get configmap my-config -o yaml
  #+END_SRC

  #+RESULTS:
  #+begin_example
  apiVersion: v1
  data:
    status: decent
  kind: ConfigMap
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","data":{"status":"decent"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"my-config","namespace":"rising"}}
    creationTimestamp: "2024-05-28T14:25:08Z"
    name: my-config
    namespace: rising
    resourceVersion: "2248050"
    uid: 96e72faa-5ecb-4cc6-83d4-01217d2c0803
  #+end_example

- Deploy a Pod that uses the ConfigMap:
  #+BEGIN_SRC shell
  cat <<EOF | kubectl apply -f -
  apiVersion: v1
  kind: Pod
  metadata:
    name: config-pod
    namespace: rising
  spec:
    containers:
    - name: config-container
      image: alpine
      command: ["sh", "-c", 'echo Status is \$STATUS && sleep 3600']
      env:
      - name: STATUS
        valueFrom:
          configMapKeyRef:
            name: my-config
            key: status
  EOF
  #+END_SRC

  #+RESULTS:
  : pod/config-pod created

- Access the logs of the Pod:
  #+BEGIN_SRC shell
    kubectl wait --for=condition=Ready pod/config-pod -n rising
    kubectl -n rising logs config-pod -c config-container
  #+END_SRC

  #+RESULTS:
  : pod/config-pod condition met
  : Status is decent

- Clean everything up:
  #+BEGIN_SRC shell
  kubectl -n rising delete pod config-pod
  kubectl -n rising delete configmap my-config
  #+END_SRC

  #+RESULTS:
  : pod "config-pod" deleted
  : configmap "my-config" deleted

** Secret =S1= - Create a Secret and use it in a Pod, then delete it
- Create a secret
  #+BEGIN_SRC shell
  cat <<EOF | kubectl apply -f -
  apiVersion: v1
  kind: Secret
  metadata:
    name: my-secret
    namespace: rising
  type: Opaque
  data:
    username: $(echo -n "admin" | base64)
    password: $(echo -n "password" | base64)
  EOF
  #+END_SRC

  #+RESULTS:
  : secret/my-secret created

- Inspect the secret:
  #+BEGIN_SRC shell
  kubectl -n rising get secret my-secret -o yaml
  #+END_SRC

  #+RESULTS:
  #+begin_example
  apiVersion: v1
  data:
    password: cGFzc3dvcmQ=
    username: YWRtaW4=
  kind: Secret
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","data":{"password":"cGFzc3dvcmQ=","username":"YWRtaW4="},"kind":"Secret","metadata":{"annotations":{},"name":"my-secret","namespace":"rising"},"type":"Opaque"}
    creationTimestamp: "2024-05-28T15:12:17Z"
    name: my-secret
    namespace: rising
    resourceVersion: "2252306"
    uid: e604704a-ac9b-4964-b3cd-8e09ebc856e9
  type: Opaque
  #+end_example

- Attach the secret to a Pod:
  #+BEGIN_SRC shell
    cat <<EOF | kubectl apply -f -
    apiVersion: v1
    kind: Pod
    metadata:
      name: secret-pod
      namespace: rising
    spec:
      containers:
      - name: secret-container
        image: alpine
        command: ["sh", "-c", 'echo Username is \$USERNAME && echo Password is \$PASSWORD && sleep 3600']
        env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: username
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: password    
    EOF
  #+END_SRC

  #+RESULTS:
  : pod/secret-pod created

- Inspect the Pod:
  #+BEGIN_SRC shell
  kubectl -n rising describe pod secret-pod
  #+END_SRC

  #+RESULTS:
  #+begin_example
  Name:             secret-pod
  Namespace:        rising
  Priority:         0
  Service Account:  default
  Node:             kubeadm-worker1/192.168.38.11
  Start Time:       Tue, 28 May 2024 17:12:44 +0200
  Labels:           <none>
  Annotations:      <none>
  Status:           Running
  IP:               10.244.1.46
  IPs:
    IP:  10.244.1.46
  Containers:
    secret-container:
      Container ID:  containerd://2c554736fa23a4dee900ea5f4f8d8164e49b5da8c948a8ea91c7f865e16869ce
      Image:         alpine
      Image ID:      docker.io/library/alpine@sha256:77726ef6b57ddf65bb551896826ec38bc3e53f75cdde31354fbffb4f25238ebd
      Port:          <none>
      Host Port:     <none>
      Command:
        sh
        -c
        echo Username is $USERNAME && echo Password is $PASSWORD && sleep 3600
      State:          Running
        Started:      Tue, 28 May 2024 17:12:46 +0200
      Ready:          True
      Restart Count:  0
      Environment:
        USERNAME:  <set to the key 'username' in secret 'my-secret'>  Optional: false
        PASSWORD:  <set to the key 'password' in secret 'my-secret'>  Optional: false
      Mounts:
        /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-lt9vg (ro)
  Conditions:
    Type              Status
    Initialized       True 
    Ready             True 
    ContainersReady   True 
    PodScheduled      True 
  Volumes:
    kube-api-access-lt9vg:
      Type:                    Projected (a volume that contains injected data from multiple sources)
      TokenExpirationSeconds:  3607
      ConfigMapName:           kube-root-ca.crt
      ConfigMapOptional:       <nil>
      DownwardAPI:             true
  QoS Class:                   BestEffort
  Node-Selectors:              <none>
  Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                               node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
  Events:
    Type    Reason     Age   From               Message
    ----    ------     ----  ----               -------
    Normal  Scheduled  5s    default-scheduler  Successfully assigned rising/secret-pod to kubeadm-worker1
    Normal  Pulling    4s    kubelet            Pulling image "alpine"
    Normal  Pulled     3s    kubelet            Successfully pulled image "alpine" in 1.184s (1.184s including waiting)
    Normal  Created    3s    kubelet            Created container secret-container
    Normal  Started    3s    kubelet            Started container secret-container
  #+end_example

- Access the logs of the Pod:
  #+BEGIN_SRC shell
  kubectl wait --for=condition=Ready pod/secret-pod -n rising
  kubectl -n rising logs secret-pod -c secret-container
  #+END_SRC

  #+RESULTS:
  : pod/secret-pod condition met
  : Username is admin
  : Password is password

- Clean everything up:
  #+BEGIN_SRC shell
  kubectl -n rising delete pod secret-pod
  kubectl -n rising delete secret my-secret
  #+END_SRC

  #+RESULTS:
  : pod "secret-pod" deleted
  : secret "my-secret" deleted
  
